[[themes]]
name = "midnight"

[themes.palette]
background     = "#1e1e2e"
foreground     = "#cdd6f4"
black          = "#45475a"
red            = "#f38ba8"
green          = "#a6e3a1"
yellow         = "#f9e2af"
blue           = "#89b4fa"
magenta        = "#cba4f7"
cyan           = "#89dceb"
white          = "#bac2de"
bright_black   = "#585b70"
bright_white   = "#a6adc8"
bright_red     = "#eba0ac"
bright_green   = "#94e2d5"
bright_yellow  = "#f2cdcd"
bright_blue    = "#b4befe"
bright_magenta = "#f5c2e7"
bright_cyan    = "#89dceb"

[themes.component_style]
block_title       = { fg = "Magenta", modifiers = ["Bold"] }
border            = { fg = "BrightBlack" }
playback_status   = { fg = "Green", modifiers = ["Bold"] }
playback_track    = { fg = "BrightWhite", modifiers = ["Bold"] }
playback_artists  = { fg = "Cyan" }
playback_album    = { fg = "Yellow" }
playback_genres   = { fg = "BrightBlack", modifiers = ["Italic"] }
playback_metadata = { fg = "BrightBlack" }
playback_progress_bar          = { fg = "Black", bg = "Magenta" }
playback_progress_bar_unfilled = { bg = "BrightBlack" }
current_playing   = { fg = "Green", modifiers = ["Bold"] }
page_desc         = { fg = "Cyan", modifiers = ["Bold"] }
playlist_desc     = { fg = "BrightBlack", modifiers = ["Italic"] }
table_header      = { fg = "Blue", modifiers = ["Bold"] }
selection         = { fg = "Black", bg = "Magenta", modifiers = ["Bold"] }
secondary_row     = { fg = "BrightBlack" }
like              = { fg = "Red" }
lyrics_playing    = { fg = "Green", modifiers = ["Bold"] }
lyrics_played     = { fg = "BrightBlack" }
